add sambamba markdup sample log files
ewels/MultiQC_TestData pull request #192
Opened 2021-04-27 22:01 UTC by gartician

2021-04-27 22:24 UTC, ewels requested changes
Nice, thank you! Please move into a subdirectory though, eg. `sambamba/markdup` rather than `sambambamarkdup`.

Also if you can add another subdirectory with the version of sambamba that you used that's always nice 👍🏻 Though actually it says it in these logs so not such a big deal.

Finally, if you're feeling keen, a short `README.md` file in the directory explaining how you generated the files (commands used etc)  is a nice addition.. 😁

2021-04-27 23:07 UTC, gartician commented
Thanks for the suggestions, the organization looks better now.
Is it a good idea to also make similar changes to the original PR in `ewels/MultiQC`? e.g. `MultiQC/multiqc/modules/sambamba/markdup.py`

2021-04-28 05:56 UTC, ewels commented
Great! Ah yes please, I'll add a comment there.

x-ref https://github.com/ewels/MultiQC/pull/1417

2021-04-28 05:56 UTC, ewels approved these changes

2021-04-28 05:57 UTC, merged